import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { inter, lora, merriweather } from "@/components/ui/fonts";
import "./globals.css";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-body antialiased",
          merriweather.variable,
          lora.variable,
        )}
        // adding fonts using tailwind-merge helper funtion. Now can declare "font-headings", "font-body" AND font-body is declared on body as default
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          {/* </ThemeProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
